### ISSUE TITLE
Wrong frequency value returned by I2cController.frequency

### ISSUE THREAD

**Issue by marccheneau** [eblot/pyftdi#128]
Hi there.

First of all I wish to express my gratitude for the amazing job! I am a newbie to programming embedded devices and I intend to stay so as it's not my core activity. Your incredibly easy-to-use library just spared me weeks of works!

To the fact now: when configuring the frequency of an I2C controller, the value specified by the user is multiplied by 3/2 internally before being sent over to Ftdi.open_mpsse_from_url. I guess there is a good reason for that.
But when I want to read out the frequency after configuration, I would have expected to get back the "physical" frequency. For instance, if I configure the controller for using 100 kHz and then read out the configured value, I get 150 kHz instead of 100 kHz.
Or am I missing something?

**Comment by eblot** [comment]
Hi, thanks -  a lot.

Well, I think that's a bug - the frequency you read back out.

The reason for the 3:2 ratio is because of the way the FTDI works. A 3-phase clock is used for I2C bus feature, and the FTDI clock needs to be modified so that the SW requested frequency is actually achieved on the physical I2C bus.

I may have forgotten to update the read back API to manage this kludge, I will fix it. Thanks for the report.

**Comment by marccheneau** [comment]
Ok, great. Thanks for the explanation and for the quick reply!

**Comment by eblot** [comment]
If you could give a try to the last version, as I do not have the HW at hand to test it... Thanks.

**Comment by marccheneau** [comment]
Sure. Right away.

**Comment by marccheneau** [comment]
I just tested the last version and it seems to do the job. I could talk to an I2C slave device and I do get back the frequency I configured. Thanks.

**Comment by eblot** [comment]
Ok, thanks for the feedback, and good catch!

**Comment by marccheneau** [comment]
You're welcome! A tiny contribution to a big and great project ;)
