### ISSUE TITLE
JTAG shift register problem

### ISSUE THREAD

**Issue by RiccardoFrancescato** [eblot/pyftdi#50]
Hi,
i have noticed that with some target i have problem with te result of the reading operation.
The shift/read function does not always read correctly the TDO any one have suggestions to fix this problem?

**Comment by frekr1** [comment]
Are you using shift_register method into JtagController class? I found a little issue in that when param use_last=True. Last bit was corrupted due to 1 TCK missing. 
To make it working correctly I needed to simply comment the lines where byte_count, pos and bit_count are recalculated (together with if len(bs) != length check ) and then force a further transition with the command RW_BITS_TMS_PVE_NVE.
